import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: '#f8f9fa',
        paddingTop: 20,
    },
    header: {
        padding: 16,
        backgroundColor: '#004aad',
        alignItems: 'center',
    },
    headerText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#fff',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        marginVertical: 10,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#222',
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#007bff',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 8,
    },
    addButtonText: {
        color: '#fff',
        marginLeft: 6,
        fontWeight: '600',
    },
    card: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        padding: 14,
        marginHorizontal: 16,
        marginVertical: 6,
        borderRadius: 12,
        elevation: 2,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
    },
    cardText: {
        fontSize: 14,
        color: '#555',
        marginTop: 2,
    },
    cardActions: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 8,
    },
    editBtn: {
        backgroundColor: '#28a745',
        padding: 8,
        borderRadius: 8,
        marginRight: 6,
    },
    deleteBtn: {
        backgroundColor: '#dc3545',
        padding: 8,
        borderRadius: 8,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#fff',
        width: '85%',
        padding: 20,
        borderRadius: 12,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 12,
        color: '#222',
    },
    input: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        padding: 10,
        marginVertical: 6,
    },
    dropdown: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        padding: 10,
        marginVertical: 6,
    },
    dropdownText: {
        color: '#333',
    },
    modalBtnRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 14,
    },
    saveBtn: {
        backgroundColor: '#007bff',
        padding: 10,
        borderRadius: 8,
        flex: 1,
        marginRight: 6,
        alignItems: 'center',
    },
    cancelBtn: {
        backgroundColor: '#6c757d',
        padding: 10,
        borderRadius: 8,
        flex: 1,
        marginLeft: 6,
        alignItems: 'center',
    },
    btnText: {
        color: '#fff',
        fontWeight: '600',
    },
    selectModal: {
        backgroundColor: '#fff',
        borderRadius: 10,
        width: '80%',
        padding: 20,
    },
    selectItem: {
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    selectText: {
        fontSize: 16,
        color: '#333',
    },
});
